
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./components/Header/Header";
import Footer from "./components/Footer/Footer";
import BottomFooter from "./components/Footer/BottomFooter";
import ContextProvider from "./components/ContextProvider/ContextProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {

  return (
    <html lang="en">
      <body className={inter.className}>
        <ContextProvider>
          <main className="max-w-[1440px] m-auto sm:px-10 px-0">
            <Header />
            {children}
          </main>
          <Footer />
          <BottomFooter />
        </ContextProvider>
      </body>
    </html>
  );
}
