
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./components/Header/Header";
import Footer from "./components/Footer/Footer";
import ContextProvider from "./components/ContextProvider/ContextProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {

  return (
    <html lang="en">
      <body className={inter.className}>
        <ContextProvider>
          <Header />
          <main className="max-w-[1440px] m-auto xl:px-20 md:px-10 sm:px-5 px-3">
            {children}
          </main>
          <Footer />
        </ContextProvider>
      </body>
    </html>
  );
}
